# Enable Block-Based Effects
enable-block-effects: true

# Enable Particle-Based Effects
enable-particle-effects: true

# Enable Vehicle Trails for Riders
vehicle-trail-effects: true

# Enable Trail Effects while Gliding
elytra-trail-effects: true

# These are your particle colors
# Example for Red: 255,56,56
particle-rgb-values:
 - 255,56,56
 - 255,145,56
 - 255,248,55
 - 134,255,54
 - 53,255,211
 - 52,140,255
 - 126,51,255
 - 220,50,255
 - 255,49,145
 
# Amount of Particles per Block
# Movements.
particle-count: 10
 
# The material a block changes to under a player
replacement-material: GOLD_BLOCK

# Rainbow Effect replaces the replacement block
do-rainbow-effect: true

# "Rainbow" Dye Colors
# See: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/DyeColor.html
wool-dye-colors:
 - RED
 - ORANGE
 - YELLOW
 - GREEN
 - BLUE
 - PURPLE
 - PINK

# Protected blocks
protected-blocks:
 - BEDROCK
 - TNT